jquery_lang_js.prototype.lang.fr ={
"NAME":"NOM",
"DATE":"DATE",
"TYPE":"TYPE",
"SIZE":"TAILLE",
"Rename":"Renommer",
"Copy":"Copier",
"Paste":"Coller",
"Genres":"Genres",
"Forgot password":"Mot de passe oublié",
"Password hint answer":"Réponse de l'indice",
"Your password hint is":"Votre indice",
"Incorrect password, please try again":"Mot de passe incorrect",
"New password field is at least 8 characters":"Le mdp doit contenir au moins 8 caractères.",
"New password and old password do not match":"Les mots de passe ne concordent pas.",
"Old password incorrect. Please try again.":"L'ancien mot de passe est incorrect. Veuillez réessayer.",
"Select a WiFi network":"Sélectionnez un réseau WiFi.",
"Please select at least one item":"Sélectionnez les éléments pour restaurer les réglages d'usine.",
"Reset selected item(s) to factory default?":"Réinitialiser le nom Wi-Fi d'usine par défaut",
"Password and Confirm password have to be the same":"Le mot de passe et sa confirmation doivent être identiques.",
"Admin Log in":"Connexion administrateur",
"Change Wi-Fi Settings":"Modifier les paramètres Wi-Fi",
"Configure the Wireless Media Drive Network":"Configurer le réseau sans fil du Wireless Media Drive",
"Wireless Network Name (WiFi SSID)":"Nom réseau ss fil (SSID WiFi)",
"Security":"Sécurité",
"Password":"Mot de passe",
"Network Name":"Nom de réseau",
"Back":"Retour",
"Change Admin Password":"Modifier le mot de passe administrateur",
"Connect To Internet":"Se connecter à Internet",
"If hint does not help, press and hold Media Drive power button for 10 seconds to restore factory settings and reset password.":"Si l'indice ne résout rien, appuyez sur le bouton d'alimentation du lecteur Media Drive et maintenez-le enfoncé pendant 10 secondes pour rétablir les réglages d'usine et réinitialiser le mot de passe.",
"Admin Password":"Mot de passe administrateur",
"To reset your password provide your current password":"Pour réinitialiser votre mdp, fournissez votre mdp actuel.",
"Old password":"Ancien mdp",
"New password":"Nouveau mdp",
"show characters":"afficher caract",
"Password must be 5 or 13 characters":"Le mot de passe Wi-Fi doit contenir entre 5 et 13 caractères.",
"Password must have at least 8-63 characters":"Le mot de passe doit contenir au moins 8 caractères.",
"Confirm password":"Confirmer le mdp",
"Provide a hint incase Admin forgets the password":"Indice en cas d'oubli du mpd par l'admin",
"Cancel":"Annuler",
"OK":"OK",
"Connect to the Internet":"Se connecter à Internet",
"Choose WiFi Network":"Choisir un réseau WiFi",
"Password:":"Mot de passe:",
"USB Access":"Accès USB",
"Off":"Arrêt",
"On":"Marche",
"Reset to Factory Settings":"Rétablir les réglages d'usine",
"Choose the items you would like to reset back to factory settings.":"Choisir les éléments pour rétablir les paramètres d'usine",
"This will not erase your files.":"Cette opération n'effacera pas vos fichiers.",
"Reset WiFi (SSID) name to factory default":"Réinitialiser le nom Wi-Fi (SSID) d'usine par défaut",
"Reset Media Drive WiFi password":"Réinitialiser le mdp Wi-Fi du lecteur Media Drive",
"Reset Admin password to admin":"Rétablir le mot de passe d'administrateur admin",
"Forget all Wi-Fi networks and their passwords":"Oublier tous les réseaux Wi-Fi et leurs mots de passe",
"Play":"Lecture",
"Add to playlist":"Ajouter à la sélection",
"Add to Now playing list":"Ajouter à la liste en cours d'écoute",
"Cannot duplicate playlist name, choose another name":"Impossible de dupliquer le nom de la sélection. Choisissez un autre nom.",
"Name field is required.":"Champ de nom requis",
"More songs by this artist":"Plus de titres de cet artiste",
"MUSIC":"MUSIQUE",
"Song":"Chanson",
"Artist":"Artiste",
"Artists":"Artistes",
"Albums":"Albums",
"Time":"Heure",
"Please login using your password":"Se connecter avec un mdp",
"Remove":"Supprimer",
"Recent":"Récent",
"Songs":"Chansons",
"Playlists":"Sélect.",
"Queue":"Attente",
"Playlist Name":"Nom de la sélection",
"Song Count":"Nbre de chansons",
"Name":"Nom",
"Playlist 1":"Sélection 1",
"Playlist 2":"Sélection 2",
"Playlist 3":"Sélection 3",
"Files":"Fichiers",
"Photos":"Photos",
"Videos":"Vidéos",
"Music":"Musique",
"Upload":"Télécharger",
"Settings":"Paramètres",
"Help":"Aide",
"Capacity":"Capacité",
"Available":"Disponible",
"Download":"Télécharg.",
"Delete":"Supprimer",
"Please download the SanDisk Wireless Media Drive app for more functionality from your Android marketplace":"Plus de fonctions ? Téléchargez SanDisk Wireless Media Drive depuis le Marché Android.",
"Please download the SanDisk Wireless Media Drive app for more functionality from the app store":"Plus de fonctions ? Téléchargez SanDisk Wireless Media Drive depuis l'App Store.",
"Are you sure you want to delete these file(s)?":"Voulez-vous vraiment supprimer ce ou ces fichier(s) ?",
"File type not recognized":"Type de fichier non reconnu",
"Target and souce folders cannot be the same":"Les dossiers source et cible doivent être différents.",
"Please refer to the quick start guide for the default password":"Reportez-vous au Guide de mise en route rapide pour connaître le mot de passe par défaut.",
"Incomplete response":"Réponse incomplète",
"Format Media Drive":"Formater le lecteur Media Drive",
"FormatConfirmMessage":"Le formatage effacera tous les fichiers enregistrés sur le lecteur Media Drive. Appuyez sur OK pour continuer.",
"FormatConfirmTitle":"Formater le lecteur Wireless Media Drive",
"FormatingMessage":"Formatage en cours",
"confirm-firmware-upgrade-message":"Un nouveau micrologiciel est prêt à être installé. Installer maintenant ?",
"firmware-upgrade-title":"Mise à jour du micrologiciel",
"firmware-upgrade-message":"Veuillez patienter…",
"FirmwareUpgrdeWaitingMsg":"Mise à jour. Attendez le redémarrage du lecteur Media Drive,  puis allez sur les paramètres WIFI de votre ordinateur pour vous reconnecter au lecteur.",
"FirmwareIsLastVersion":"Vous utilisez le tout dernier micrologiciel.",
"Pictures":"Images",
"Can not add more items to this playlist":"Impossible d'ajouter davantage d'éléments à cette sélection",
"Uploaded successfully":"Téléchargement réussi",
"Message":"Message",
"Upgrade Media Drive:":"Mettre à jour Media Drive :",
"Yes":"Oui",
"Unknown file type":"Type de fichier inconnu",
"Unknown artist":"Artiste inconnu",
"Unknown album":"Album inconnu",
"Unknown genre":"Genre inconnu",
"The song is already in the playlist":"La chanson figure déjà dans la sélection.",
"Your browser needs Flash plug-in to play music. Click OK to download and install":"Veuillez installer Adobe® Flash® Player pour diffuser de la musique dans votre navigateur. ",
"Wireless Media Drive is unavailable temporarily. Please try again later":"Wireless Media Drive est temporairement indisponible. Veuillez réessayer ultérieurement.",
"FormatCompleteMsg":"Fin du formatage. Actualiser la page Web avant de continuer.",
"FormatFail":"Échec du formatage. Veuillez réessayer.",
"Folder downloads are not supported. Please select files instead. ":"Les téléchargements de dossiers ne sont pas pris en charge. Veuillez plutôt sélectionner des fichiers. ",
"Permission Denied":"Autorisation refusée",
"Incorrect answer":"Réponse incorrecte",
"Add one song at-a-time to the playlist":"Ajouter une chanson à la fois à la sélection",
"Charging":"Chargement",
"ConnectSuccessfully":"Veuillez patienter pendant que le lecteur Media Drive réinitialise sa connexion Wi-Fi. Veuillez vous reconnecter au lecteur depuis les paramètres réseau de votre ordinateur.",
"ConnectFailed":"Échec de la connexion. Veuillez réessayer.",
"Search result":"R. rech.",
"Password field is required":"Champ de mot de passe requis",
"Admin Log out":"Déconnexion administrateur",
"Press OK to logout":"Appuyer sur OK pour se déconnecter",
"File name or path not supported.":"Nom de fichier ou de chemin non pris en charge",
"About":"À propos de",
"Privacy Policy":"Politique de confidentialité",
"The file size is larger than 4 GB. Please reduce the file size or reformat to FAT32":"La taille du fichier est supérieure à 4 Go. Veuillez réduire la taille de fichier ou reformer en FAT32 :",
"New":"Nouveau",
"Select music content to play":"Sélectionner un contenu musical à lire",
"SETTINGS":"PARAMÈTRES",
"ADMIN SETTINGS":"PARAMÈTRES ADMINISTRATIFS",
"Getting Started":"Mise en route",
"Online Support":"Assistance en ligne",
"Upgrade":"Mettre à jour",
"Web App Version":"Version de l'application Web",
"Legal":"Informations légales",
"No files selected":"Aucun fichier sélectionné",
"Folders cannot be downloaded":"Les dossiers ne peuvent pas être téléchargés.",
"Upgrade in Process":"Mise à jour en cours",
"Create Folder":"Créer un dossier",
"Folder name cannot be empty":"Le nom de dossier ne peut pas être vide.",
"Media Drive Battery:":"Batterie lecteur média :",
"Language":"Langue",
"Should the video file not playback properly, download the file to your computer and play with your favorite video player.":"Si le fichier vidéo ne se lit pas correctement, téléchargez le fichier vers votre ordinateur et utilisez votre lecteur vidéo favori.",
"Don't show message again.":"Ne plus afficher ce message",
"PHOTOS":"PHOTOS",
"VIDEOS":"VIDÉOS",
"Password hint":"Indice de mot de passe",
"Video Playback Hint":"Indice de lecture des vidéos",
"Upload Failed":"échec du téléchargement",
"Uploading":"téléchargement",
"Copying":"copie",
"Deleting":"effacer",
"SanDisk is a trademark of SanDisk Corporation registered in the United States and other countries. SanDisk Connect is a trademark of SanDisk Corporation. All other trademarks are the property of their respective owners.":"SanDisk est une marque de SanDisk Corporation, déposée aux États-Unis et dans d'autres pays. SanDisk Connect est une marque de SanDisk Corporation. Toutes les autres marques commerciales sont la propriété de leurs détenteurs respectifs.",
"©2013 SanDisk Corporation. All rights reserved.":"©2013 SanDisk Corporation. Tous droits réservés.",
"In progress…":"Chargement…",
"No search results found":"Aucun résultat trouvé",
"ChangeAdminSuccess":"Modification du mot de passe administrateur réussie",
"ChangeSSIDSuccess":"Changements de connexion et de mot de passe Wi-Fi réussi. Attendez le redémarrage du lecteur Media Drive et reconnectez-vous.",
"ChangeSSIDFail":"Échec des changements de connexion et de mot de passe Wi-Fi.",
"LoginSuccess":"Connexion réussie",
"UpgradeFirmwareFail":"Échec de la mise à niveau du micrologiciel",
"ResetSuccess":"Réinitialisation réussie. Attendez le redémarrage du lecteur Media Drive,  puis allez sur les paramètres WIFI de votre ordinateur pour vous reconnecter au lecteur.",
"ResetFail":"Échec de la réinitialisation Veuillez réessayer.",
"MscOpen":"Accès USB ouvert",
"MscClose":"Accès USB fermé",
"MscFail":"Échec du traitement de l'accès USB. Veuillez réessayer.",
"Full screen":"Plein écran",
"Copy selected":"Copie sélectionné",
"Close":"Fermer",
"Slideshow":"Diaporama",
"For a better experience please launch the Media Drive App":"Pour une meilleure expérience s'il vous plaît lancer l'media drive application",
"Get the Media Drive app":"Télécharger l'Media Drive application",
"WifiOn":"Wi-Fi ON",
"WifiOff":"Wi-Fi OFF",
"WifiFailed":"Connexion WiFi échoué. S'il vous plaît essayer de nouveau.",
"File Name:":"Nom du fichier:",
"Would you like to download the file to your computer?":"Voulez-vous télécharger le fichier sur votre ordinateur?",
"USBOnTitle":"Le lecteur Media Drive est connecté au port USB.",
"USBOnMessage":"Accès sans fil au lecteur Media Drive impossible en cas de branchement USB. Pour accéder au contenu sans fil, déconnectez le lecteur du port USB.",
"UploadSuccessMsg":"{0} fichiers téléchargement avec succès"
};

var langWordJson=function(){
	return jquery_lang_js.prototype.lang.fr;
};
