jquery_lang_js.prototype.lang.en ={
"NAME":"NAME",
"DATE":"DATE",
"TYPE":"TYPE",
"SIZE":"SIZE",
"Rename":"Rename",
"Copy":"Copy",
"Paste":"Paste",
"Genres":"Genres",
"Forgot password":"Forgot password",
"Password hint answer":"Password hint answer",
"Your password hint is":"Your password hint is",
"Incorrect password, please try again":"Incorrect password",
"New password field is at least 8 characters":"New password field is at least 8 characters",
"New password and old password do not match":"Passwords do not match",
"Old password incorrect. Please try again.":"Old password incorrect. Please try again.",
"Select a WiFi network":"Select a WiFi network",
"Please select at least one item":"Select items to restore to factory settings.",
"Reset selected item(s) to factory default?":"Reset selected item(s) to factory default?",
"Password and Confirm password have to be the same":"Password and Confirm password have to be the same",
"Admin Log in":"Admin Log in",
"Change Wi-Fi Settings":"Change Wi-Fi Settings",
"Configure the Wireless Media Drive Network":"Configure the Wireless Media Drive Network",
"Wireless Network Name (WiFi SSID)":"Wireless Network Name (WiFi SSID)",
"Security":"Security",
"Password":"Password",
"Network Name":"Network Name",
"Back":"Back",
"Change Admin Password":"Change Admin Password",
"Connect To Internet":"Connect To Internet",
"If hint does not help, press and hold Media Drive power button for 10 seconds to restore factory settings and reset password.":"If hint does not help, press and hold Media Drive power button for 10 seconds to restore factory settings and reset password.",
"Admin Password":"Admin Password",
"To reset your password provide your current password":"To reset your password provide your current password",
"Old password":"Old password",
"New password":"New password",
"show characters":"show characters",
"Password must be 5 or 13 characters":"Wi-Fi password must contain between 5 or 13 characters.",
"Password must have at least 8-63 characters":"Password must contain at least 8 characters.",
"Confirm password":"Confirm password",
"Provide a hint incase Admin forgets the password":"Provide a hint incase Admin forgets the password",
"Cancel":"Cancel",
"OK":"OK",
"Connect to the Internet":"Connect to the Internet",
"Choose WiFi Network":"Choose WiFi Network",
"Password:":"Password:",
"USB Access":"USB Access",
"Off":"off",
"On":"on",
"Reset to Factory Settings":"Reset to Factory Settings",
"Choose the items you would like to reset back to factory settings.":"Choose the items you would like to reset back to factory settings.",
"This will not erase your files.":"This will not erase your files.",
"Reset WiFi (SSID) name to factory default":"Reset WiFi (SSID) name to factory default",
"Reset Media Drive WiFi password":"Reset Media Drive WiFi password",
"Reset Admin password to admin":"Reset Admin password to admin",
"Forget all Wi-Fi networks and their passwords":"Forget all Wi-Fi networks and their passwords",
"Play":"Play",
"Add to playlist":"Add to playlist",
"Add to Now playing list":"Add to Now playing list",
"Cannot duplicate playlist name, choose another name":"Cannot duplicate playlist name, choose another name",
"Name field is required.":"Name field is required",
"More songs by this artist":"More songs by this artist",
"MUSIC":"MUSIC",
"Song":"Song",
"Artist":"Artist",
"Artists":"Artists",
"Albums":"Albums",
"Time":"Time",
"Please login using your password":"Please login using your password",
"Remove":"Remove",
"Recent":"Recent",
"Songs":"Songs",
"Playlists":"Playlists",
"Queue":"Queue",
"Playlist Name":"Playlist Name",
"Song Count":"Song count",
"Name":"Name",
"Playlist 1":"Playlist 1",
"Playlist 2":"Playlist 2",
"Playlist 3":"Playlist 3",
"Files":"Files",
"Photos":"Photos",
"Videos":"Videos",
"Music":"Music",
"Upload":"Upload",
"Settings":"Settings",
"Help":"Help",
"Capacity":"Capacity",
"Available":"Available",
"Download":"Download",
"Delete":"Delete",
"Please download the SanDisk Wireless Media Drive app for more functionality from your Android marketplace":"Please download the SanDisk Wireless Media Drive app for more functionality from your Android marketplace",
"Please download the SanDisk Wireless Media Drive app for more functionality from the app store":"Please download the SanDisk Wireless Media Drive app for more functionality from the app store",
"Are you sure you want to delete these file(s)?":"Are you sure you want to delete these file(s)?",
"File type not recognized":"File type not recognized",
"Target and souce folders cannot be the same":"Target and source folders cannot be the same",
"Please refer to the quick start guide for the default password":"Please refer to the quick start guide for the default password",
"Incomplete response":"Incomplete response",
"Format Media Drive":"Format Media Drive",
"FormatConfirmMessage":"Formatting will erase all files on the Media Drive. Tap OK to continue.",
"FormatConfirmTitle":"Format Wireless Media Drive",
"FormatingMessage":"Formatting in progress",
"confirm-firmware-upgrade-message":"New Firmware is ready to install. Install now?",
"firmware-upgrade-title":"Firmware Upgrade",
"firmware-upgrade-message":"Please stand by…",
"FirmwareUpgrdeWaitingMsg":"Upgrading.  Wait for Media Drive to restart, then go to your computer's WiFi Settings to reconnect to the Drive.",
"FirmwareIsLastVersion":"You are running the latest Firmware.",
"Pictures":"Pictures",
"Can not add more items to this playlist":"Can not add more items to this playlist",
"Uploaded successfully":"Uploaded successfully",
"Message":"Message",
"Upgrade Media Drive:":"Upgrade Media Drive:",
"Yes":"Yes",
"Unknown file type":"Unknown file type",
"Unknown artist":"Unknown artist",
"Unknown album":"Unknown album",
"Unknown genre":"Unknown genre",
"The song is already in the playlist":"The song is already in the playlist",
"Your browser needs Flash plug-in to play music. Click OK to download and install":"Please install Adobe® Flash® Player to stream music in your browser.",
"Wireless Media Drive is unavailable temporarily. Please try again later":"Wireless Media Drive is unavailable temporarily. Please try again later",
"FormatCompleteMsg":"Formatting complete. Refresh the webpage to continue.",
"FormatFail":"Formatting failed. Please try again.",
"Folder downloads are not supported. Please select files instead. ":"Folder downloads are not supported. Please select files instead. ",
"Permission Denied":"Permission denied",
"Incorrect answer":"Incorrect answer",
"Add one song at-a-time to the playlist":"Add one song at-a-time to the playlist",
"Charging":"Charging",
"ConnectSuccessfully":"Please wait while Media Drive is resetting its WiFi. Please reconnect to the Drive from your computer's network settings.",
"ConnectFailed":"Connection failed. Try again.",
"Search result":"Search result",
"Password field is required":"Password field is required",
"Admin Log out":"Admin Log out",
"Press OK to logout":"Press OK to logout",
"File name or path not supported.":"File name or path not supported",
"About":"About",
"Privacy Policy":"Privacy Policy",
"The file size is larger than 4 GB. Please reduce the file size or reformat to FAT32":"The file size is larger than 4 GB. Please reduce the file size or reformat to FAT32':",
"New":"New",
"Select music content to play":"Select music content to play",
"SETTINGS":"SETTINGS",
"ADMIN SETTINGS":"ADMIN SETTINGS",
"Getting Started":"Getting Started",
"Online Support":"Online Support",
"Upgrade":"Upgrade",
"Web App Version":"Web App Version",
"Legal":"Legal",
"No files selected":"No files selected",
"Folders cannot be downloaded":"Folders cannot be downloaded",
"Upgrade in Process":"Upgrade in Process",
"Create Folder":"Create Folder",
"Folder name cannot be empty":"Folder name cannot be empty",
"Media Drive Battery:":"Media Drive Battery:",
"Language":"Language",
"Should the video file not playback properly, download the file to your computer and play with your favorite video player.":"Should the video file not playback properly, download the file to your computer and play with your favorite video player.",
"Don't show message again.":"Don't show message again.",
"PHOTOS":"PHOTOS",
"VIDEOS":"VIDEOS",
"Password hint":"Password hint",
"Video Playback Hint":"Video Playback Hint",
"Upload Failed":"Upload failed",
"Uploading":"Uploading",
"Copying":"Copying",
"Deleting":"Deleting",
"SanDisk is a trademark of SanDisk Corporation registered in the United States and other countries. SanDisk Connect is a trademark of SanDisk Corporation. All other trademarks are the property of their respective owners.":"SanDisk is a trademark of SanDisk Corporation registered in the United States and other countries. SanDisk Connect is a trademark of SanDisk Corporation. All other trademarks are the property of their respective owners.",
"©2013 SanDisk Corporation. All rights reserved.":"©2013 SanDisk Corporation. All rights reserved.",
"In progress…":"In progress…",
"No search results found":"No search results found",
"ChangeAdminSuccess":"Admin password changed successfully",
"ChangeSSIDSuccess":"Wi-Fi and Wi-Fi password changes successful.Wait for Media Drive to restart, then reconnect.",
"ChangeSSIDFail":"Wi-Fi and Wi-Fi password changes failed.",
"LoginSuccess":"Login successful",
"UpgradeFirmwareFail":"Firmware upgrade failed",
"ResetSuccess":"Reset successful. Wait for Media Drive to restart, then go to your computer's WiFi Settings to reconnect to the Drive.",
"ResetFail":"Reset failed. Try again.",
"MscOpen":"USB Access open",
"MscClose":"USB Access closed",
"MscFail":"USB Access process failed. Try again.",
"Full screen":"Full screen",
"Copy selected":"Copy selected",
"Close":"Close",
"Slideshow":"Slideshow",
"For a better experience please launch the Media Drive App":"For a better experience please launch the Media Drive App",
"Get the Media Drive app":"Get the Media Drive app",
"WifiOn":"Wi-Fi ON",
"WifiOff":"Wi-Fi OFF",
"WifiFailed":"Wi-Fi Connection failed. Please try",
"File Name:":"File Name:",
"Would you like to download the file to your computer?":"Would you like to download the file to your computer?",
"USBOnTitle":"Media Drive Connected To USB",
"USBOnMessage":"Cannot access Media Drive wirelessly while it is plugged into USB. To access content wirelessly, disconnect the Drive from USB.",
"UploadSuccessMsg":"{0} files uploaded successfully"
};

var langWordJson=function(){
	return jquery_lang_js.prototype.lang.en;
};
