jquery_lang_js.prototype.lang.it ={
"NAME":"NOME",
"DATE":"DATA",
"TYPE":"TIPO",
"SIZE":"DIMENSIONI",
"Rename":"Rinomina",
"Copy":"Copia",
"Paste":"Incolla",
"Genres":"Genere",
"Forgot password":"Password dimenticata",
"Password hint answer":"Risposta al suggerimento password",
"Your password hint is":"Il suggerimento password è",
"Incorrect password, please try again":"Password errata",
"New password field is at least 8 characters":"La Nuova password deve avere almeno 8 caratteri",
"New password and old password do not match":"Le password non corrispondono",
"Old password incorrect. Please try again.":"Vecchia password non corretta. Riprovare.",
"Select a WiFi network":"Seleziona una rete wi-fi",
"Please select at least one item":"Selezionare le voci da ripristinare alle impostazioni di fabbrica.",
"Reset selected item(s) to factory default?":"Resettare elementi selezionati alle impostazioni di fabbrica?",
"Password and Confirm password have to be the same":"I campi Password e Conferma Password deve coincidere",
"Admin Log in":"Accesso Amministratore",
"Change Wi-Fi Settings":"Modifica Impostazioni wi-fi",
"Configure the Wireless Media Drive Network":"Configurare la rete wireless del Media Drive",
"Wireless Network Name (WiFi SSID)":"Nome rete wireless (WiFi SSID)",
"Security":"Sicurezza",
"Password":"Password",
"Network Name":"Nome della rete",
"Back":"Indietro",
"Change Admin Password":"Modifica password amministratore",
"Connect To Internet":"Collega ad internet",
"If hint does not help, press and hold Media Drive power button for 10 seconds to restore factory settings and reset password.":"Se il suggerimento non aiuta, tenere premuto il tasto di accensione Media Drive per 10 secondi per ripristinare le impostazioni di fabbrica e resettare la password.",
"Admin Password":"Password amministratore",
"To reset your password provide your current password":"Per resettare la password, fornire quella attuale",
"Old password":"Vecchia password",
"New password":"Nuova password",
"show characters":"mostra caratteri",
"Password must be 5 or 13 characters":"La password Wi-Fi deve contenere 5 o 13 caratteri.",
"Password must have at least 8-63 characters":"La password deve contenere almeno 8 caratteri.",
"Confirm password":"Conferma password",
"Provide a hint incase Admin forgets the password":"Fornire suggerimento se password dimenticata",
"Cancel":"Annulla",
"OK":"OK",
"Connect to the Internet":"Collega ad internet",
"Choose WiFi Network":"Scegli rete wi-fi",
"Password:":"Password:",
"USB Access":"Accesso USB",
"Off":"off",
"On":"on",
"Reset to Factory Settings":"Ripristina alle impostazioni di fabbrica",
"Choose the items you would like to reset back to factory settings.":"Scegli elementi da riportare alle impostazioni iniziali.",
"This will not erase your files.":"Questa procedura non cancellerà i file.",
"Reset WiFi (SSID) name to factory default":"Riporta nome wi-fi (SSID) a impostazioni di fabbrica",
"Reset Media Drive WiFi password":"Resetta password wi-fi di Media Drive",
"Reset Admin password to admin":"Ripristina password amministratore a admin",
"Forget all Wi-Fi networks and their passwords":"Dimentica tutte le reti wi-fi e le relative password",
"Play":"Riproduci",
"Add to playlist":"Aggiungi a playlist",
"Add to Now playing list":"Aggiungi a elenco In riproduzione",
"Cannot duplicate playlist name, choose another name":"Impossibile duplicare il nome della playlist, scegliere un altro nome",
"Name field is required.":"Il campo nome è obbligatorio",
"More songs by this artist":"Maggiori brani di questo artista",
"MUSIC":"MUSICA",
"Song":"Brano",
"Artist":"Artista",
"Artists":"Artisti",
"Albums":"Album",
"Time":"Ora",
"Please login using your password":"Accedi con password",
"Remove":"Rimuovi",
"Recent":"Recente",
"Songs":"Brani",
"Playlists":"Playlist",
"Queue":"Coda",
"Playlist Name":"Nome playlist",
"Song Count":"Conteggio brani",
"Name":"Nome",
"Playlist 1":"Playlist 1",
"Playlist 2":"Playlist 2",
"Playlist 3":"Playlist 3",
"Files":"File",
"Photos":"Foto",
"Videos":"Video",
"Music":"Musica",
"Upload":"Carica",
"Settings":"Impostazioni",
"Help":"Guida",
"Capacity":"Capacità",
"Available":"Disponibile",
"Download":"Scarica",
"Delete":"Elimina",
"Please download the SanDisk Wireless Media Drive app for more functionality from your Android marketplace":"Scaricare l'app per Wireless Media Drive per più funzionalità dal Mercato Android",
"Please download the SanDisk Wireless Media Drive app for more functionality from the app store":"Scaricare l'app per Wireless Media Drive dallo app store per più funzionalità ",
"Are you sure you want to delete these file(s)?":"Sei sicuro di voler eliminare questi file?",
"File type not recognized":"Tipo di file non riconosciuto",
"Target and souce folders cannot be the same":"La cartella di origine e destinazione non può essere la stessa",
"Please refer to the quick start guide for the default password":"Fare riferimento alla guida rapida per la password predefinita",
"Incomplete response":"Risposta incompleta",
"Format Media Drive":"Formatta Media Drive",
"FormatConfirmMessage":"La formattazione cancella tutti i file sul Media Drive. Toccare OK per continuare",
"FormatConfirmTitle":"Formatta Wireless Media Drive",
"FormatingMessage":"Formattazione in corso",
"confirm-firmware-upgrade-message":"Nuovo firmware pronto per l'installazione. Installare ora?",
"firmware-upgrade-title":"Aggiornamento firmware",
"firmware-upgrade-message":"Attendere, prego...",
"FirmwareUpgrdeWaitingMsg":"In fase di aggiornamento. Attendere che il Media Drive si riavvii, quindi entrare nelle Impostazioni WiFi del Computer per ricollegarsi al dispositivo.",
"FirmwareIsLastVersion":"È presente l'ultima versione del firmware.",
"Pictures":"Immagini",
"Can not add more items to this playlist":"Impossibile aggiungere altre voci a questa playlist",
"Uploaded successfully":"Upload eseguito con successo",
"Message":"Messaggio",
"Upgrade Media Drive:":"Aggiorna Media Drive:",
"Yes":"Sì   ",
"Unknown file type":"Tipo di file sconosciuto",
"Unknown artist":"Artista ignoto",
"Unknown album":"Album ignoto",
"Unknown genre":"Genere ignoto",
"The song is already in the playlist":"Il brano è già nella playlist",
"Your browser needs Flash plug-in to play music. Click OK to download and install":"Si prega di installare Adobe® Flash® Player per ascoltare la musica nel browser.",
"Wireless Media Drive is unavailable temporarily. Please try again later":"Wireless Media Drive al momento non è disponibile. Riprovare più tardi.",
"FormatCompleteMsg":"Formattazione completata. Aggiorna la pagina Web prima di continuare",
"FormatFail":"Formattazione fallita. Riprovare.",
"Folder downloads are not supported. Please select files instead. ":"Il download di cartelle non è supportato. Selezionarne solo i file. ",
"Permission Denied":"Autorizzazione negata",
"Incorrect answer":"Risposta errata",
"Add one song at-a-time to the playlist":"Aggiungere un brano per volta alla playlist",
"Charging":"In carica",
"ConnectSuccessfully":"Si prega di attendere mentre il Media Drive ripristina il WiFi. Si prega di riconnettersi al Drive usando le impostazioni di rete del proprio computer.",
"ConnectFailed":"Connessione non riuscita. Riprova.",
"Search result":"Risultato ricerca",
"Password field is required":"Il campo Password è obbligatorio",
"Admin Log out":"Disconnessione Amministratore",
"Press OK to logout":"Premere OK per disconnettersi",
"File name or path not supported.":"Nome file o percorso non supportati",
"About":"Info su",
"Privacy Policy":"Informativa sulla privacy",
"The file size is larger than 4 GB. Please reduce the file size or reformat to FAT32":"La dimensione del file è superiore a 4 GB. Ridurre la dimensione del file o riformattare in FAT32':",
"New":"Nuovo",
"Select music content to play":"Seleziona musica da riprodurre",
"SETTINGS":"IMPOSTAZIONI",
"ADMIN SETTINGS":"IMPOSTAZIONI AMMINISTRATORE",
"Getting Started":"Operazioni preliminari",
"Online Support":"Assistenza online",
"Upgrade":"Aggiorna",
"Web App Version":"Versione app web",
"Legal":"Legale",
"No files selected":"Nessun file selezionato",
"Folders cannot be downloaded":"Le cartelle non possono essere scaricate",
"Upgrade in Process":"Aggiornamento in corso",
"Create Folder":"Crea cartella",
"Folder name cannot be empty":"Il campo nome cartella non può essere vuoto",
"Media Drive Battery:":"Batteria Media Drive:",
"Language":"Lingua",
"Should the video file not playback properly, download the file to your computer and play with your favorite video player.":"Se il file video non dovesse essere riprodotto in modo corretto, scaricare il file sul proprio computer e riprodurlo con il video player preferito.",
"Don't show message again.":"Non mostrare più il messaggio.",
"PHOTOS":"FOTO",
"VIDEOS":"VIDEO",
"Password hint":"Suggerimento password",
"Video Playback Hint":"Suggerimento riproduzione video",
"Upload Failed":"caricamento non riuscito",
"Uploading":"caricamento",
"Copying":"copia",
"Deleting":"cancellare",
"SanDisk is a trademark of SanDisk Corporation registered in the United States and other countries. SanDisk Connect is a trademark of SanDisk Corporation. All other trademarks are the property of their respective owners.":"SanDisk è un marchio di SanDisk Corporation, registrato negli Stati Uniti e in altri paesi. SanDisk Connect è un marchio di SanDisk Corporation. Tutti gli altri marchi commerciali sono di proprietà dei rispettivi proprietari.",
"©2013 SanDisk Corporation. All rights reserved.":"©2013 SanDisk Corporation. Tutti i diritti riservati.",
"In progress…":"Caricamento in corso…",
"No search results found":"Nessun risultato trovato",
"ChangeAdminSuccess":"Password amministratore modificata con successo",
"ChangeSSIDSuccess":"Modifiche wi-fi e password wi-fi avvenute con successo. Attendere il riavvio di Media Drive e ricollegarsi.",
"ChangeSSIDFail":"Modifiche wi-fi e password wi-fi fallite.",
"LoginSuccess":"Accesso avvenuto con successo",
"UpgradeFirmwareFail":"Aggiornamento firmware fallito",
"ResetSuccess":"Reset avvenuto con successo. Attendere che il Media Drive si riavvii, quindi entrare nelle Impostazioni WiFi del Computer per ricollegarsi al dispositivo.",
"ResetFail":"Reset fallito. Riprova.",
"MscOpen":"Accesso USB aperto",
"MscClose":"Accesso USB chiuso",
"MscFail":"Elaborazione Accesso USB fallita. Riprova.",
"Full screen":"Schermo Intero",
"Copy selected":"Copia selezionato",
"Close":"Chiudere",
"Slideshow":"Presentazione",
"For a better experience please launch the Media Drive App":"Per una migliore esperienza si prega di lanciare l'media drive app",
"Get the Media Drive app":"Scarica l'media drive applicazione",
"WifiOn":"Wi-Fi ON",
"WifiOff":"Wi-Fi OFF",
"WifiFailed":"Connessione Wi-Fi non è riuscita. Riprova.",
"File Name:":"Nome del file:",
"Would you like to download the file to your computer?":"Volete scaricare il file sul tuo computer?",
"USBOnTitle":"Media Drive collegato a USB",
"USBOnMessage":"Impossibile accedere a Media Drive in wireless mentre è collegato a USB. Per accedere ai contenuti in wireless, disconnettere il Drive da USB.",
"UploadSuccessMsg":"{0} file caricati con successo"
};

var langWordJson=function(){
	return jquery_lang_js.prototype.lang.it;
};
