jquery_lang_js.prototype.lang.de ={
"NAME":"NAME",
"DATE":"DATUM",
"TYPE":"TYP",
"SIZE":"GRÖSSE",
"Rename":"Umbenennen",
"Copy":"Kopieren",
"Paste":"Einfügen",
"Genres":"Genres",
"Forgot password":"Kennwort vergessen",
"Password hint answer":"Kennwort-Hinweisantwort",
"Your password hint is":"Ihr Kennworthinweis ist",
"Incorrect password, please try again":"Ungültiges Kennwort",
"New password field is at least 8 characters":"Das neue Kennwort muss aus mindestens 8 Zeichen bestehen",
"New password and old password do not match":"Kennwörter stimmen nicht überein",
"Old password incorrect. Please try again.":"Altes Kennwort ist falsch. Versuchen Sie es noch einmal.",
"Select a WiFi network":"Ein WiFi-Netzwerk auswählen",
"Please select at least one item":"Wählen Sie Elemente aus, die auf die Werkseinstellungen zurückgesetzt werden sollen.",
"Reset selected item(s) to factory default?":"Markierte(s) Element(e) auf Werkseinstellungen zurücksetzen?",
"Password and Confirm password have to be the same":"Kennwort und Bestätigung müssen übereinstimmen",
"Admin Log in":"Admin-Login",
"Change Wi-Fi Settings":"WiFi-Einstellungen ändern",
"Configure the Wireless Media Drive Network":"Das Wireless Media Drive Network konfigurieren",
"Wireless Network Name (WiFi SSID)":"Wireless Networkname (WiFi SSID)",
"Security":"Sicherheit",
"Password":"Kennwort",
"Network Name":"Netzwerkname",
"Back":"Zurück",
"Change Admin Password":"Admin-Kennwort ändern",
"Connect To Internet":"Internetverbindung herstellen",
"If hint does not help, press and hold Media Drive power button for 10 seconds to restore factory settings and reset password.":"Sollte der Hinweis nicht ausreichen, halten Sie den Ein-/Ausschalter 10 Sekunden lang gedrückt, um den Media Drive mitsamt Kennwort auf die Werkseinstellungen zurückzusetzen.",
"Admin Password":"Admin-Kennwort",
"To reset your password provide your current password":"Geben Sie zum Zurücksetzen Ihr aktuelles Kennwort ein",
"Old password":"Altes Kennwort",
"New password":"Neues Kennwort",
"show characters":"Zeichen anzeigen",
"Password must be 5 or 13 characters":"Das Wi-Fi-Kennwort muss aus 5 bis 13 Zeichen bestehen.",
"Password must have at least 8-63 characters":"Das Kennwort muss aus mindestens 8 Zeichen bestehen.",
"Confirm password":"Kennwort bestätigen",
"Provide a hint incase Admin forgets the password":"Einen Hinweis eingeben, falls Admin das Kennwort vergisst",
"Cancel":"Abbrechen",
"OK":"OK",
"Connect to the Internet":"Internetverbindung herstellen",
"Choose WiFi Network":"WiFi-Netzwerk auswählen",
"Password:":"Kennwort:",
"USB Access":"USB-Zugriff",
"Off":"aus",
"On":"ein",
"Reset to Factory Settings":"Auf Werkseinstellungen zurücksetzen",
"Choose the items you would like to reset back to factory settings.":"Elemente zum Zurücksetzen auf Werkseinstellung auswählen.",
"This will not erase your files.":"Dadurch werden Ihre Dateien nicht gelöscht.",
"Reset WiFi (SSID) name to factory default":"WiFi-Namen (SSID) auf Werkseinstellungen zurücksetzen",
"Reset Media Drive WiFi password":"Media Drive WiFi-Kennwort zurücksetzen",
"Reset Admin password to admin":"Admin-Kennwort auf admin zurücksetzen",
"Forget all Wi-Fi networks and their passwords":"Alle WiFi-Zugriffspunkte und ihre Kennwörter löschen",
"Play":"Abspielen",
"Add to playlist":"Der Wiedergabeliste hinzufügen",
"Add to Now playing list":"Zur Liste „Aktuelle Wiedergabe“",
"Cannot duplicate playlist name, choose another name":"Name der Playliste kann nicht dupliziert werden. Wählen Sie einen anderen Namen.",
"Name field is required.":"Namensfeld ist erforderlich",
"More songs by this artist":"Mehr Titel dieses Interpreten",
"MUSIC":"MUSIK",
"Song":"Titel",
"Artist":"Interpret",
"Artists":"Interpreten",
"Albums":"Alben",
"Time":"Uhrzeit",
"Please login using your password":"Verwenden Sie zum Einloggen Ihr Kennwort",
"Remove":"Entfernen",
"Recent":"Zuletzt",
"Songs":"Titel",
"Playlists":"Wiedergabelisten",
"Queue":"Schlange",
"Playlist Name":"Wiedergabeliste-Name",
"Song Count":"Titelzähler",
"Name":"Name",
"Playlist 1":"Wiedergabeliste 1",
"Playlist 2":"Wiedergabeliste 2",
"Playlist 3":"Wiedergabeliste 3",
"Files":"Dateien",
"Photos":"Fotos",
"Videos":"Videos",
"Music":"Musik",
"Upload":"Upload",
"Settings":"Einstellungen",
"Help":"Hilfe",
"Capacity":"Kapazität",
"Available":"Verfügbar",
"Download":"Download",
"Delete":"Löschen",
"Please download the SanDisk Wireless Media Drive app for more functionality from your Android marketplace":"Für mehr Funktionen, SanDisk Wireless Media Drive App vom Android Marketplace herunterladen",
"Please download the SanDisk Wireless Media Drive app for more functionality from the app store":"Für mehr Funktionen, SanDisk Wireless Media Drive App vom Android Marketplace herunterladen",
"Are you sure you want to delete these file(s)?":"Sind Sie sicher, dass Sie diese Datei(en) löschen möchten?",
"File type not recognized":"Dateityp nicht erkannt",
"Target and souce folders cannot be the same":"Ziel- und Quellordner dürfen nicht identisch sein",
"Please refer to the quick start guide for the default password":"Das Standardkennwort finden Sie in der Kurzanleitung.",
"Incomplete response":"Unvollständige Antwort",
"Format Media Drive":"Media Drive formatieren",
"FormatConfirmMessage":"Durch Formatieren des Media Drive werden alle darauf gespeicherten Inhalte gelöscht. Tippen Sie auf OK, um fortzusetzen.",
"FormatConfirmTitle":"Wireless Media Drive formatieren",
"FormatingMessage":"Formatierung läuft",
"confirm-firmware-upgrade-message":"Neue Firmware kann installiert werden. Jetzt installieren?",
"firmware-upgrade-title":"Firmware-Upgrade",
"firmware-upgrade-message":"Bitte warten...",
"FirmwareUpgrdeWaitingMsg":"Aktualisierung wird durchgeführt. Gehen Sie nach dem Neustart des Media Drive zu den Wi-Fi-Einstellungen des Computers, um die Verbindung mit dem Gerät wieder herzustellen.",
"FirmwareIsLastVersion":"Das Gerät führt die neueste Firmware aus.",
"Pictures":"Bilder",
"Can not add more items to this playlist":"Mehr Titel können zu dieser Wiedergabeliste nicht hinzugefügt werden",
"Uploaded successfully":"Erfolgreich hochgeladen",
"Message":"Nachricht",
"Upgrade Media Drive:":"Media Drive aktualisieren:",
"Yes":"Ja",
"Unknown file type":"Unbekannter Dateityp",
"Unknown artist":"Unbekannter Interpret",
"Unknown album":"Unbekanntes Album",
"Unknown genre":"Unbekanntes Genre",
"The song is already in the playlist":"Dieser Titel ist bereits in der Wiedergabeliste",
"Your browser needs Flash plug-in to play music. Click OK to download and install":"Bitte installieren Sie den Adobe ® Flash ® Player, um Musik in Ihrem Browser zu streamen.",
"Wireless Media Drive is unavailable temporarily. Please try again later":"Wireless Media Drive ist vorübergehend nicht verfügbar. Versuchen Sie es später noch einmal",
"FormatCompleteMsg":"Formatierung abgeschlossen. Aktualisieren Sie die Webseite, um fortzusetzen.",
"FormatFail":"Formatierung fehlgeschlagen. Versuchen Sie es noch einmal.",
"Folder downloads are not supported. Please select files instead. ":"Ordner-Downloads sind nicht unterstützt. Wählen Sie stattdessen Dateien aus. ",
"Permission Denied":"Erlaubnis verweigert",
"Incorrect answer":"Ungültige Antwort",
"Add one song at-a-time to the playlist":"Fügen Sie jeweils einen Titel zur Wiedergabeliste hinzu",
"Charging":"Laden des Akkus",
"ConnectSuccessfully":"Warten Sie bitte, bis Media Drive sein WiFi zurückgesetzt hat. Stellen Sie dann eine Neuverbindung zum Drive über die Netzwerkeinstellungen Ihres Computers her.",
"ConnectFailed":"Verbindung fehlgeschlagen. Versuchen Sie es noch einmal.",
"Search result":"Suchergebnis",
"Password field is required":"Kennwortfeld ist erforderlich",
"Admin Log out":"Admin-Logout",
"Press OK to logout":"Zum Ausloggen OK drücken",
"File name or path not supported.":"Dateiname oder -pfad nicht unterstützt",
"About":"Info über",
"Privacy Policy":"Datenschutzrichtlinie",
"The file size is larger than 4 GB. Please reduce the file size or reformat to FAT32":"Datei ist größer als 4 GB. Dateigröße reduzieren oder auf FAT32' umformatieren:",
"New":"Neu",
"Select music content to play":"Musikinhalte für Wiedergabe wählen",
"SETTINGS":"EINSTELLUNGEN",
"ADMIN SETTINGS":"ADMIN-EINSTELLUNGEN",
"Getting Started":"Erste Schritte",
"Online Support":"Online-Support",
"Upgrade":"Aktualisieren",
"Web App Version":"Web App Version",
"Legal":"Rechtliche Hinweise",
"No files selected":"Keine Dateien ausgewählt",
"Folders cannot be downloaded":"Ordner können nicht heruntergeladen werden",
"Upgrade in Process":"Upgrade läuft",
"Create Folder":"Ordner erstellen",
"Folder name cannot be empty":"Ordnername darf nicht leer sein",
"Media Drive Battery:":"Media Drive Akku:",
"Language":"Sprache",
"Should the video file not playback properly, download the file to your computer and play with your favorite video player.":"Sollte bei der Video-Wiedergabe ein Problem auftreten, laden Sie die Datei auf Ihren Computer und spielen Sie es dort mit einem Player ab.",
"Don't show message again.":"Diese Meldung nicht erneut anzeigen.",
"PHOTOS":"FOTOS",
"VIDEOS":"VIDEOS",
"Password hint":"Kennworthinweis",
"Video Playback Hint":"Video-Wiedergabehinweis",
"Upload Failed":"Upload fehlgeschlagen",
"Uploading":"uploading",
"Copying":"kopieren",
"Deleting":"Löschen",
"SanDisk is a trademark of SanDisk Corporation registered in the United States and other countries. SanDisk Connect is a trademark of SanDisk Corporation. All other trademarks are the property of their respective owners.":"SanDisk ist eine in den Vereinigten Staaten und anderen Ländern eingetragene Marke der SanDisk Corporation. SanDisk Connect ist eine Marke der SanDisk Corporation. Alle anderen Marken sind Eigentum ihrer jeweiligen Inhaber.",
"©2013 SanDisk Corporation. All rights reserved.":"©2013 SanDisk Corporation. Alle Rechte vorbehalten.",
"In progress…":"Daten werden geladen…",
"No search results found":"Keine Suchergebnisse",
"ChangeAdminSuccess":"Admin-Kennwort erfolgreich geändert",
"ChangeSSIDSuccess":"Wi-Fi und Wi-Fi-Kennwort erfolgreich geändert. Stellen Sie nach dem Neustart des Media Drive die Verbindung wieder her.",
"ChangeSSIDFail":"Änderung von Wi-Fi und Wi-Fi-Kennwort fehlgeschlagen.",
"LoginSuccess":"Login erfolgreich",
"UpgradeFirmwareFail":"Firmware-Aktualisierung ist fehlgeschlagen",
"ResetSuccess":"Zurücksetzung erfolgreich. Gehen Sie nach dem Neustart des Media Drive zu den Wi-Fi-Einstellungen des Computers, um die Verbindung mit dem Gerät wieder herzustellen.",
"ResetFail":"Zurücksetzung fehlgeschlagen. Versuchen Sie es noch einmal.",
"MscOpen":"USB-Zugang geöffnet",
"MscClose":"USB-Zugang geschlossen",
"MscFail":"USB-Zugriff fehlgeschlagen. Versuchen Sie es noch einmal.",
"Full screen":"Vollbild",
"Copy selected":"Kopieren ausgewählt",
"Close":"schließen",
"Slideshow":"Diashow",
"For a better experience please launch the Media Drive App":"Für eine bessere Erfahrung starten Sie bitte die Media Drive App",
"Get the Media Drive app":"Holen Sie sich die Media Drive App",
"WifiOn":"Wi-Fi ON",
"WifiOff":"Wi-Fi OFF",
"WifiFailed":"WiFi Verbindung fehlgeschlagen. Bitte versuchen Sie es erneut",
"File Name:":"Dateiname:",
"Would you like to download the file to your computer?":"Möchten Sie die Datei auf Ihren Computer herunterzuladen?",
"USBOnTitle":"Media Drive ist über UBS verbunden",
"USBOnMessage":"Auf den Media Drive kann nicht kabellos zugegriffen werden, solange er an den USB, Anschluss angeschlossen ist. Trennen Sie den Drive vom USB-Anschluss, um kabellos auf Inhalte zuzugreifen.",
"UploadSuccessMsg":"{0} Dateien erfolgreich hochgeladen"
};

var langWordJson=function(){
	return jquery_lang_js.prototype.lang.de;
};
