jquery_lang_js.prototype.lang.es ={
"NAME":"NOMBRE",
"DATE":"FECHA",
"TYPE":"TIPO",
"SIZE":"TAMAÑO",
"Rename":"Cambiar nombre",
"Copy":"Copiar",
"Paste":"Pegar",
"Genres":"Géneros",
"Forgot password":"¿Olvidó la contraseña?",
"Password hint answer":"Respuesta pista de contraseña",
"Your password hint is":"Pista contr.",
"Incorrect password, please try again":"Contraseña incorrecta",
"New password field is at least 8 characters":"El campo Nueva contraseña es de 8 caract. máx.",
"New password and old password do not match":"Las contraseñas no coinciden",
"Old password incorrect. Please try again.":"Contraseña anterior incorrecta. Inténtelo de nuevo.",
"Select a WiFi network":"Seleccionar una red WiFi",
"Please select at least one item":"Seleccione elementos para restaurar los ajustes predeterminados.",
"Reset selected item(s) to factory default?":"¿Restablecer elementos seleccionados a valores de fábrica?",
"Password and Confirm password have to be the same":"Los campos Contraseña y Confirmar contraseña tienen que ser iguales",
"Admin Log in":"Inicio sesión admin.",
"Change Wi-Fi Settings":"Cambiar ajustes WiFi",
"Configure the Wireless Media Drive Network":"Configurar la red de Wireless Media Drive",
"Wireless Network Name (WiFi SSID)":"Nom. red inalámbr. (WiFi SSID)",
"Security":"Seguridad",
"Password":"Contraseña",
"Network Name":"Nombre de red",
"Back":"Atrás",
"Change Admin Password":"Cambiar contraseña de administrador",
"Connect To Internet":"Conectarse a Internet",
"If hint does not help, press and hold Media Drive power button for 10 seconds to restore factory settings and reset password.":"Si la pista no ayuda, mantenga pulsado el botón de encendido de Media Drive durante 10 segundos para restaurar los ajustespredeterminados y restablecer la contraseña.",
"Admin Password":"Contraseña de administrador",
"To reset your password provide your current password":"Para restablecer contraseña, indique la contraseña actual",
"Old password":"Contr. anterior",
"New password":"Contras. nueva",
"show characters":"mostrar caract.",
"Password must be 5 or 13 characters":"La contraseña Wi-Fi debe tener entre 5 o 13 caracteres.",
"Password must have at least 8-63 characters":"La contraseña debe tener al menos 8 caracteres.",
"Confirm password":"Conf. contras.",
"Provide a hint incase Admin forgets the password":"Dé una pista si administr. olvida la contraseña",
"Cancel":"Cancelar",
"OK":"Aceptar",
"Connect to the Internet":"Conectarse a Internet",
"Choose WiFi Network":"Elegir red WiFi",
"Password:":"Contraseña:",
"USB Access":"Acceso USB",
"Off":"desactivar",
"On":"activar",
"Reset to Factory Settings":"Restablecer ajustes predeterminados",
"Choose the items you would like to reset back to factory settings.":"Elija los elementos para restablecer a valores de fábrica.",
"This will not erase your files.":"Esto no borrará los archivos.",
"Reset WiFi (SSID) name to factory default":"Restablecer el nombre WiFi (SSID) a valores de fábrica",
"Reset Media Drive WiFi password":"Restablecer contraseña WiFi de unidad multimedia",
"Reset Admin password to admin":"Restablecer la contraseña de administrador a admin",
"Forget all Wi-Fi networks and their passwords":"Olvidar todas las redes WiFi y sus contraseñas",
"Play":"Reproducir",
"Add to playlist":"Añadir a lista de reproducción",
"Add to Now playing list":"Añadir a lista reproducción actual",
"Cannot duplicate playlist name, choose another name":"No se puede duplicar el nombre de la lista de reproducción. Elija otro nombre",
"Name field is required.":"El campo de nombre es obligatorio",
"More songs by this artist":"Más canciones de este intérprete",
"MUSIC":"MÚSICA",
"Song":"Canción",
"Artist":"Intérprete",
"Artists":"Intérpr.",
"Albums":"Álbumes",
"Time":"Hora",
"Please login using your password":"Inicie sesión con contras.",
"Remove":"Quitar",
"Recent":"Reciente",
"Songs":"Cancns.",
"Playlists":"L. repr.",
"Queue":"Cola",
"Playlist Name":"Nombre lista reprod.",
"Song Count":"Rec. canciones",
"Name":"Nombre",
"Playlist 1":"Lista reproduc. 1",
"Playlist 2":"Lista reproduc. 2",
"Playlist 3":"Lista reproduc. 3",
"Files":"Archivos",
"Photos":"Fotos",
"Videos":"Vídeos",
"Music":"Música",
"Upload":"Cargar",
"Settings":"Ajustes",
"Help":"Ayuda",
"Capacity":"Capacidad",
"Available":"Disponible",
"Download":"Descargar",
"Delete":"Eliminar",
"Please download the SanDisk Wireless Media Drive app for more functionality from your Android marketplace":"Descargue la aplicación SanDisk Wireless Media Drive desde Android Marketplace.",
"Please download the SanDisk Wireless Media Drive app for more functionality from the app store":"Descargue la aplicación SanDisk Wireless Media Drive desde App Store.",
"Are you sure you want to delete these file(s)?":"¿Está seguro de que desea eliminar estos archivos?",
"File type not recognized":"Tipo de archivo no reconocido",
"Target and souce folders cannot be the same":"Las carpetas de origen y destino no pueden ser la misma",
"Please refer to the quick start guide for the default password":"Consulte en la guía de inicio rápido la contraseña predeterminada",
"Incomplete response":"Respuesta incompleta",
"Format Media Drive":"Formatear unidad multimedia",
"FormatConfirmMessage":"Al formatear, se borrarán todos los archivos de Media Drive. Puntee Aceptar para continuar.",
"FormatConfirmTitle":"Formatear Wireless Media Drive",
"FormatingMessage":"Formateo en curso",
"confirm-firmware-upgrade-message":"El nuevo firmware está listo para instalar. ¿Instalar ahora?",
"firmware-upgrade-title":"Actualización de firmware",
"firmware-upgrade-message":"Espere...",
"FirmwareUpgrdeWaitingMsg":"Actualizando. Espere a que el Media Drive reinicie, luego vaya a Configuración de WiFi para reconectar la unidad.",
"FirmwareIsLastVersion":"Está ejecutando el firmware más reciente.",
"Pictures":"Imágenes",
"Can not add more items to this playlist":"No se pueden añadir más elementos a esta lista de reproducción",
"Uploaded successfully":"Cargado correctamente",
"Message":"Mensaje",
"Upgrade Media Drive:":"Actual. unidad multimedia:",
"Yes":"Sí",
"Unknown file type":"Tipo de archivo desconocido",
"Unknown artist":"Intérpr. descon.",
"Unknown album":"Álbum desconoc.",
"Unknown genre":"Género desconoc.",
"The song is already in the playlist":"La canción ya en la lista de reproducción",
"Your browser needs Flash plug-in to play music. Click OK to download and install":"Please install Adobe ® Flash ® Player para reproducir música en tu navegador. ",
"Wireless Media Drive is unavailable temporarily. Please try again later":"Wireless Media Drive no está disponible en este momento. Inténtelo de nuevo más adelante.",
"FormatCompleteMsg":"Formateo completo. Recargue la página web para continuar.",
"FormatFail":"Error al formatear. Inténtelo de nuevo.",
"Folder downloads are not supported. Please select files instead. ":"Las descargas de carpetas no se admiten. Seleccione archivos en su lugar. ",
"Permission Denied":"Permiso denegado",
"Incorrect answer":"Respuesta incorrecta",
"Add one song at-a-time to the playlist":"Añada una canción a la vez a la lista de reproducción",
"Charging":"Cargando",
"ConnectSuccessfully":"Espere mientras Media Drive restablece el WiFi. Vuelva a conectarse a la unidad desde los ajustes de red del ordenador.",
"ConnectFailed":"Error en la conexión. Inténtelo de nuevo.",
"Search result":"Rs. bús.",
"Password field is required":"La contraseña es necesaria",
"Admin Log out":"Cierre sesión admistr.",
"Press OK to logout":"Pulse Aceptar para cerrar sesión",
"File name or path not supported.":"Nombre de archivo o ruta no admitidos",
"About":"Acerca de",
"Privacy Policy":"Política de privacidad",
"The file size is larger than 4 GB. Please reduce the file size or reformat to FAT32":"El tamaño del archivo es mayor que 4 GB. Reduzca el tamaño del archivo o reformatee a FAT32:",
"New":"Nuevo",
"Select music content to play":"Selecc. contenido musical para reprod.",
"SETTINGS":"AJUSTES",
"ADMIN SETTINGS":"AJUSTES DE ADMINISTRADOR",
"Getting Started":"Primeros pasos",
"Online Support":"Soporte técnico en línea",
"Upgrade":"Actualizar",
"Web App Version":"Versión de aplicación web",
"Legal":"Legal",
"No files selected":"No hay archivos seleccionados",
"Folders cannot be downloaded":"Las carpetas no se pueden descargar",
"Upgrade in Process":"Actualización en curso",
"Create Folder":"Crear carpeta",
"Folder name cannot be empty":"El nombre de carpeta no puede estar vacío",
"Media Drive Battery:":"Batería unidad multimed.:",
"Language":"Idioma",
"Should the video file not playback properly, download the file to your computer and play with your favorite video player.":"Si el archivo de vídeo no se reproduce correctamente, descargue el archivo en el ordenador y reprodúzcalo con su reproductor de vídeo favorito.",
"Don't show message again.":"No volver a mostrar el mensaje",
"PHOTOS":"FOTOS",
"VIDEOS":"VÍDEOS",
"Password hint":"Pista de contraseña",
"Video Playback Hint":"Pista de reproducción de vídeo",
"Upload Failed":"Error cargando archivo",
"Uploading":"Cargando",
"Copying":"Copiando",
"Deleting":"Borrando",
"SanDisk is a trademark of SanDisk Corporation registered in the United States and other countries. SanDisk Connect is a trademark of SanDisk Corporation. All other trademarks are the property of their respective owners.":"SanDisk es una marca comercial de SanDisk Corporation, registrada en Estados Unidos y en otros países. SanDisk Connect es una marca comercial de SanDisk Corporation. Todas las demás marcas comerciales pertenecen a sus respectivos propietarios.",
"©2013 SanDisk Corporation. All rights reserved.":"©2013 SanDisk Corporation. Todos los derechos reservados.",
"In progress…":"Cargando…",
"No search results found":"No se han encontrado resultados de búsqueda",
"ChangeAdminSuccess":"Contraseña de admin. cambiada correctamente",
"ChangeSSIDSuccess":"Cambio de Wi-Fi y de contraseña Wi-Fi correcto. Espere a que se reinicie Media Drive y vuelva a conectarse.",
"ChangeSSIDFail":"Error al cambiar Wi-Fi y contraseña Wi-Fi.",
"LoginSuccess":"Inicio de sesión correcto",
"UpgradeFirmwareFail":"Error al actualizar firmware",
"ResetSuccess":"Reajuste exitoso. Espere a que el Media Drive reinicie, luego vaya a Configuración de WiFi para reconectar la unidad.",
"ResetFail":"Error al restablecer. Inténtelo de nuevo.",
"MscOpen":"Acceso USB abierto",
"MscClose":"Acceso USB cerrado",
"MscFail":"Error de proceso de acceso USB Inténtelo de nuevo.",
"Full screen":"pantalla completa",
"Copy selected":"Copie seleccionado",
"Close":"Cerrar",
"Slideshow":"Presentación de diapositivas",
"For a better experience please launch the Media Drive App":"Para una mejor experiencia por favor, inicie la media drive aplicación",
"Get the Media Drive app":"Obtener el Media Drive App",
"WifiOn":"Wi-Fi ON",
"WifiOff":"Wi-Fi OFF",
"WifiFailed":"Conexión WiFi falló. Por favor, inténtelo de nuevo.",
"File Name:":"Nombre del archivo:",
"Would you like to download the file to your computer?":"¿Quieres descargar el archivo a su computadora",
"USBOnTitle":"Media Drive conectado a USB",
"USBOnMessage":"No se puede acceder a Media Drive de forma inalámbrica si está conectado a USB. Para acceder al contenido de forma inalámbrica, desconecte la unidad de USB.",
"UploadSuccessMsg":"{0} archivos subidos con éxito"
};

var langWordJson=function(){
	return jquery_lang_js.prototype.lang.es;
};
