jquery_lang_js.prototype.lang.zh ={
	NAME:'檔案名稱',
	DATE:'最後更新日期',
	TYPE:'檔案類別',
	SIZE:'檔案大小',
	Rename:'重新命名',
	Copy:'複製',
	Paste:'貼上',
	Genres:'曲風',
	'Forgot password':'忘記密碼',
	'Password hint answer':'密碼提示解答',
	'Your password hint is':'你的密碼提示為',
	'New password field is at least 8 characters':'至少要8個字',
	'New password and old password do not match':'密碼不一致,請檢查',
	'Old password incorrect. Please try again.':'舊密碼錯誤，請確認',
	'Select a WiFi network':'請選擇一個無線網路',
	'Incorrect password, please try again':'密碼錯誤,請重新輸入',
	'Please select at least one item':'請選擇一個項目',
	'Reset selected item(s) to factory default?':'您確定要設回預設值?',
	'Password and Confirm password have to be the same':'密碼和確認密碼不一樣,請重新輸入',
	'Admin Log in':'使用者登入',
        'Change Admin Password':'變更密碼',
	'Connect To Internet':'連結網路',
	'If the hint does not help you, reset back to factory setttings by pressing and holding the power button on Wireless Media Drive for 10 seconds.':'如果提示無法幫助你,請回復到原廠設定',
	'Admin Password' :'使用者密碼',
	'To reset your password provide your current password':'請提供正確密碼來重設密碼',
	'Old password':'舊密碼',
	'New password':'新密碼',
	'show characters':'顯示密碼',
	'Password must be 5 or 13 characters':'必須為5或13個字元',
	'Password must have at least 8-63 characters':'至少輸入8~63個字',
	'Confirm password':'密碼確認',
	'Provide a hint incase Admin forgets the password':'使用者忘記密碼時,用來提示',
	'Cancel':'取消',
	'OK':'提交',
	'Connect to the Internet':'連結網路',
	'Choose WiFi Network':'選擇Wifi網路',
	'Network Name':'網路名稱',
	'Change Wi-Fi Settings':'修改Wi-Fi設定',
	'Configure the Wireless Media Drive Network':'配置Wireless Media Drive無線網路',
	'Wireless Network Name (WiFi SSID)':'無線網路名稱(WiFi SSID)',
	'Security':'安全性',
	'Password':'密碼',
	'Back':'回去',
	'Confirm password':'確認密碼',
	'USB Access':'變更MSC狀態',
	'Off':'關',
	'On':'開',
	'Reset to Factory Settings':'重置為出廠設置',
	'Choose the items you would like to reset back to factory settings.':'選擇您想要將重置為出廠設置的專案',
	'This will not erase your files.':'這不會刪除您的檔案',
	'Reset WiFi (SSID) name to factory default':'重置預設WIFI(SSID)名稱 = Wireless Media Drive 12345',
	'Reset Media Drive WiFi password':'重置開放WIFI(SSID)名稱和WIFI密碼',
	'Reset Admin password to admin':'重置使用者密碼:admin',
	'Forget all Wi-Fi networks and their passwords':'消除所有的無線存取點和密碼',
	'Play':'播放',
	'Add to playlist':'增加歌曲到清單',
	'Cannot duplicate playlist name, choose another name':'該播放清單名稱已經存在',
	'Name field is required.':'未填寫播放清單名稱.',
	'More songs by this artist':'更多這位歌手的歌曲',	
        'Add to playlist':'加至撥放清單',
        'Add to Now playing list':'加至目前播放清單',
	'MUSIC':'音樂',
	'Song':'歌名',
	'Artist':'演出者',
	'Artists':'演出者',
	'Albums':'專輯',
	'Time':'時間',
     'Please login using your password':'請先登入',
	'Remove':'刪除',
	'Recent':'最新歌曲',
	'Songs':'所有歌曲',
	'Playlists':'播放清單',
	'Queue':'正在播放的清單',
	'Playlist Name':'播放清單名稱',
	'Song Count':'清單歌曲數量',
	'Name':'名稱',
	'Playlist 1':'播放清單 1',
	'Playlist 2':'播放清單 2',
	'Playlist 3':'播放清單 3',
	'Files':'檔案',
	'Photos':'相片',
	'Videos':'影片',
	'Music':'音樂',
	'Upload':'上傳',
	'Settings':'設定',
	'Help':'幫助',
	'Capacity':'磁碟空間',
	'Available':'可使用空間',
	'Download':'下載',
	'Delete':'刪除',
	'Please download the SanDisk Wireless Media Drive app for more functionality from your Android marketplace':'請從Android市集下載特定的App來使用更多的功能',
	'Please download the SanDisk Wireless Media Drive app for more functionality from the app store':'請從Apple市集下載特定的App來使用更多的功能',
	'Are you sure you want to delete these file(s)?':'請確認是否刪除所選檔案?',
	'File type not recognized':'無法辨識的檔案類型',
	'Target and souce folders cannot be the same':'目的和來源目錄不能相同',
	'Please refer to the quick start guide for the default password':'請參閱快速入門指南的默認密碼',	
	'Format Media Drive':'格式化硬碟',
	'FormatConfirmMessage':'格式化將會刪除所有資料，請確定是否刪除？',
	'FormatConfirmTitle':'格式化',
	'FormatingMessage':'格式化中....',
	'confirm-firmware-upgrade-message':'有新版的韌體可以更新。請問現在要更新嗎？',
	'firmware-upgrade-title':'更新韌體',
	'firmware-upgrade-message':'韌體更新中，請勿關閉系統。',
	'FirmwareUpgrdeWaitingMsg':'目前會做韌體更新，網路會斷線，請不要關機，請稍後再重新連線',
	'FirmwareIsLastVersion':'沒有需要更新的版本！',
	'Pictures': '相片數',
	'Uploaded successfully':'上傳成功',
	'Can not add more items to this playlist':'您所選擇的播放清單數量與您目前所選的歌曲數目之加總超過播放清單的最高上限',
	'Message':'訊息',
	'Upgrade Media Drive:':'檢查韌體更新:',
         Yes:'確定',
	'Unknown file type':'格式不支援。',
	'Unknown artist':'未知的歌手',
	'Unknown album':'未知的專輯',
	'Unknown genre':'未知的曲風',
	'Incomplete response':'所有欄位都必須填寫',
	'The song is already in the playlist':'這首歌已存在播放清單裡',
    'Your browser needs Flash plug-in to play music. Click OK to download and install':'接下來會安裝最新版的Flash，以便使用完整功能',
	"Wireless Media Drive is unavailable temporarily. Please try again later":"超過執行時間，請再操作一次",
	'FormatCompleteMsg':'格式化完成',
	'FormatFail':'格式化失敗，訊息為：',
	'Folder downloads are not supported. Please select files instead. ': '無法下載目錄，請選擇檔案',
	'Permission Denied': '存取拒絕',
	'Incorrect answer':'提示密碼輸入錯誤',
	'Add one song at-a-time to the playlist':'您最多只能勾選一首歌加入播放清單',
	Charging:'充電中',
	'ConnectSuccessfully':'Server會斷線，請稍後再重新連線',
	'ConnectFailed':'連線失敗, 原因為:',
	'Search result':'搜尋結果',
	'Password field is required':'密碼欄位不能空白',
	'Admin Log out':'登出',
	'Press OK to logout':'按提交來做登出的動作',
	'File name or path not supported.':'檔名或路徑不支援',
	'About':'關於',
	'Version':'版本',
	'Privacy Policy':'隱私權政策',
	'The file size is larger than 4 GB. Please reduce the file size or reformat to FAT32':'來源檔案大於4GB. 請縮小檔案大小或是格式化為FAT32',
	'New':'新增',
	'Select music content to play':'請選擇音樂來播放',
	'SETTINGS':'設定',
	'ADMIN SETTINGS':'管理者設定',
	'Getting Started':'開始使用',
	'Online Support':'線上求助',
	'Upgrade':'升級',
	'Web App Version':'網頁App版本',
	'Legal':'法律條文',
	'No files selected':'沒有選擇檔案',
	'Folders cannot be downloaded':'目錄不能下載',
	'Create Folder':'建立目錄',
	'Folder name cannot be empty':'目錄名稱不能為空',
	'Media Drive Battery:':'電池資訊:',
	'Language':'語言',
	'Should the video file not playback properly, download the file to your computer and play with your favorite video player.':'假如影片沒有下載，你會需要自己下載影片來撥放',
	"Don't show message again.":"不用再提醒了",
	'PHOTOS':'相片',
	'VIDEOS':'影片',
	'Password hint':'密碼提示',
	'Video Playback Hint':'影片播放提示',
	'Upload Failed':'上傳失敗',
	'Uploading':'上傳中',
	'Copying':'複製資料中',
	'Deleting':'刪除資料中'
};

var langWordJson=function(){
	return jquery_lang_js.prototype.lang.zh;
};